### ISSUE TITLE
Problems on page content contributing.md

### ISSUE THREAD

**Issue by abadroot** [CodeClub/curriculum_documentation#9]
The statement

_"The content for the projects.codeclubworld.org can be found in the master branch and the content for the codeclubprojects.org site can be found in the new-layout branch."_

seems not to be correct.

In fact, in the **master** branch I do not see all the projects 
presented on the site [projects.codeclubworld.org](url) (for the Italian language), 
which instead I find in the **new-layout** branch.

**Comment by rik-cross** [comment]
Hi @abadroot, thanks for your message.

I think the confusion is due to the fact that going to http://projects.codeclubworld.org/ and clicking Italian actually redirects to https://codeclubprojects.org/it-IT/, and the markdown for these projects is in the `new-layout` branch.

I hope this answers your question, but please get in contact if you have any further questions.

Thanks,
Rik.

**Comment by abadroot** [comment]
Rik thank you for your reply,
what you say is just what I had already said.

The sentence remains ambiguous if one wants to contribute because it is not clear on which branch to work.
